name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup Conda
        uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: viralorthology
          environment-file: environment.yml
          auto-activate-base: false

      - name: Check format
        shell: bash -l {0}
        run: ruff format --check src

      - name: Lint
        shell: bash -l {0}
        run: ruff check src

      - name: Type check
        shell: bash -l {0}
        run: mypy --strict --disable-error-code=no-untyped-call src

      - name: Tests
        shell: bash -l {0}
        run: PYTHONPATH=src pytest
